#!/bin/bash
# dbp-pack - Enables automation for creation of DBP packages for the Dragonbox Pyra
# By Wally - 2021


if [ ! command -v mksquashfs &> /dev/null ]; then
    echo "Please install SquashFS Tools for your distribution"; exit 1;
fi

if [ ! command -v zip &> /dev/null ]; then
    echo "Please install zip for your distribution"; exit 1;
fi


# Probably better in your /dragonbox/packages folder on one of your SD cards
# This is set to $HOME so it will work on all devices for performance in compression.

DBPHOME=$HOME/DBPS

build(){


#Consistency checks
if [ -f $TARGET ]; then
    echo "Not a directory"
elif [ ! -d "$TARGET/data" ] || [ ! -d "$TARGET/icons" ] || [ ! -d "$TARGET/meta" ]; then
    echo "$TARGET is Missing data / icons or meta folder"
elif [ ! -f "$TARGET/meta/default.desktop" ]; then
    echo "$TARGET is missing Default.desktop file"
elif [ -f "$DBPHOME/$DBPNAME.dbp" ]; then
    echo "DBP already exists"
elif [ ! -d $DBPHOME ]; then
    mkdir $DBPHOME
else

echo " --- $TARGET is being packed --- "
cd "$TARGET"

#Remove .DS_Store files where Darwin is involved
if [ "$(uname)" == "Darwin" ]; then
    echo "Removing macOS Resource forks"
    find . -name .DS_Store -type f -delete ; find . -type d | xargs dot_clean -m
fi

# Set Permissions and create squashed / zipped volume
chmod -R go+rwx "$PWD/"
mksquashfs data target.sqfs -all-root -force-gid 0 -comp xz
zip -Z store -r meta.zip meta icons teasers

#append datafiles to dbpdata and output to dbpname.dbp
cat target.sqfs meta.zip > "$TARGET.dbp"
zip -A "$TARGET.dbp"

#Clean up temporary files
rm -r meta.zip target.sqfs

mv $TARGET.dbp "$DBPHOME"
echo "$TARGET.dbp has been generated successfully"
cd ..
fi
}

batch(){
    for TARGET in * ;
        do
            build "$TARGET"
        done
}

TARGET=$(echo "$1" | cut -f 1 -d '/') # Re

if [ ! -d "$TARGET" ] && [ "$1" != "batch" ]; then
    echo "Invalid directory"
elif [ "$1" == "batch" ]; then
    echo "Batch compile in progress"
    batch 
else
    build "$@"
fi